doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     127.0.0.1
        port:     5432
        dbname:   "6team"
        user:     '%env(resolve:DATABASE_USERNAME)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        charset:  UTF8

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
